// <auto-generated />
namespace Dziennik_v0._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MeasurmentModelAddDietType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MeasurmentModelAddDietType));
        
        string IMigrationMetadata.Id
        {
            get { return "202007230752275_MeasurmentModelAddDietType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
